/** Lifecycle-bound styles for the credential panel. */
import { injectStylesOnce } from './injectStyles.js'

const STYLE_TAG = 'configcenter/credentials.css'

export const PANEL_CSS = `
.dsh-config-center{box-sizing:border-box;width:min(1280px,100%);margin:0 auto;padding:28px 32px}.dsh-config-center__header{display:flex;align-items:end;justify-content:space-between;gap:24px;margin-bottom:20px}.dsh-config-center__header h1{margin:0;font-size:24px}.dsh-config-center__header p{margin:8px 0 0;color:var(--dsw-alias-label-secondary)}.dsh-config-center__tabs{display:flex;gap:4px;padding:4px;border-radius:10px;background:var(--dsw-alias-bg-module-platform,#f1f5f9)}.dsh-config-center__tabs button{border:0;border-radius:7px;background:transparent;color:var(--dsw-alias-label-secondary);padding:8px 14px;font:inherit;cursor:pointer}.dsh-config-center__tabs button.active{background:var(--dsw-alias-bg-base,#fff);color:var(--dsw-alias-label-primary);box-shadow:0 1px 3px rgba(15,23,42,.1)}.dsh-config-center__content>.dsh-cc-page{width:100%;padding:0}.dsh-config-center__content>.dti-root{padding:0}.dsh-config-center__content .dti-shell{max-width:none}@media(max-width:700px){.dsh-config-center{padding:20px 16px}.dsh-config-center__header{align-items:start;flex-direction:column}.dsh-config-center__tabs{width:100%}.dsh-config-center__tabs button{flex:1}}
.dsh-cc-page{box-sizing:border-box;width:min(1180px,100%);margin:0 auto;padding:40px 34px 64px;color:var(--dsw-alias-label-primary);font-size:14px}
.dsh-cc-header{display:flex;align-items:flex-start;justify-content:space-between;gap:24px;margin-bottom:24px}.dsh-cc-header h1{margin:0;font-size:30px;line-height:1.2;font-weight:680;letter-spacing:-.02em}.dsh-cc-header p{margin:8px 0 0;color:var(--dsw-alias-label-secondary);font-size:15px;line-height:22px}
.dsh-cc-primary{border:0;border-radius:10px;background:var(--dsw-alias-button-contrast-fill,#101116);color:var(--dsw-alias-button-contrast-label,#fff);font:inherit;font-weight:600;padding:11px 18px;display:inline-flex;align-items:center;justify-content:center;gap:7px;cursor:pointer;box-shadow:0 1px 2px rgba(0,0,0,.12)}.dsh-cc-primary:hover:not(:disabled){opacity:.9}.dsh-cc-primary:disabled{opacity:.55;cursor:default}.dsh-cc-primary span{font-size:20px;font-weight:400;line-height:14px}
.dsh-cc-help{display:flex;align-items:center;gap:14px;margin-bottom:20px;border:1px solid color-mix(in srgb,var(--dsw-alias-brand-primary,#4d6bfe) 16%,transparent);border-radius:11px;background:color-mix(in srgb,var(--dsw-alias-brand-primary,#4d6bfe) 8%,transparent);padding:15px 18px;color:var(--dsw-alias-label-primary)}.dsh-cc-code{color:var(--dsw-alias-brand-primary,#4d6bfe);font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-weight:700;font-size:18px}
.dsh-cc-search{height:50px;border:1px solid var(--dsw-alias-border-secondary,rgba(0,0,0,.14));border-radius:10px;display:flex;align-items:center;gap:10px;padding:0 15px;color:var(--dsw-alias-label-tertiary);margin-bottom:24px;background:var(--dsw-alias-bg-base,#fff)}.dsh-cc-search:focus-within{border-color:var(--dsw-alias-brand-primary,#4d6bfe);box-shadow:0 0 0 2px color-mix(in srgb,var(--dsw-alias-brand-primary,#4d6bfe) 14%,transparent)}.dsh-cc-search input{min-width:0;flex:1;border:0;outline:0;background:transparent;color:var(--dsw-alias-label-primary);font:inherit;font-size:15px}.dsh-cc-search input::placeholder{color:var(--dsw-alias-label-tertiary)}
.dsh-cc-card{overflow:hidden;border:1px solid var(--dsw-alias-border-secondary,rgba(0,0,0,.13));border-radius:13px;background:var(--dsw-alias-bg-base,#fff)}.dsh-cc-card-head{height:64px;display:flex;align-items:center;gap:9px;padding:0 22px;border-bottom:1px solid var(--dsw-alias-border-secondary,rgba(0,0,0,.11));font-size:16px}.dsh-cc-card-head span{min-width:26px;height:26px;border-radius:999px;background:var(--dsw-alias-interactive-bg-hover,rgba(0,0,0,.06));display:inline-flex;align-items:center;justify-content:center;font-size:13px}
.dsh-cc-table-wrap{overflow:auto}.dsh-cc-table{width:100%;border-collapse:collapse;table-layout:fixed}.dsh-cc-table th{height:52px;padding:0 22px;text-align:left;color:var(--dsw-alias-label-secondary);font-weight:550;background:var(--dsw-alias-bg-module-platform,rgba(0,0,0,.018));border-bottom:1px solid var(--dsw-alias-border-secondary,rgba(0,0,0,.1))}.dsh-cc-table td{height:72px;padding:0 22px;border-bottom:1px solid var(--dsw-alias-border-secondary,rgba(0,0,0,.09));vertical-align:middle}.dsh-cc-table tbody tr:last-child td{border-bottom:0}.dsh-cc-table tbody tr:hover{background:var(--dsw-alias-interactive-bg-hover,rgba(0,0,0,.025))}.dsh-cc-table th:nth-child(1){width:27%}.dsh-cc-table th:nth-child(2){width:28%}.dsh-cc-table th:nth-child(3){width:22%}.dsh-cc-table th:nth-child(4){width:15%}.dsh-cc-table th:nth-child(5){width:84px}.dsh-cc-table code{font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-size:14px;color:var(--dsw-alias-label-primary);white-space:nowrap}.dsh-cc-table time{color:var(--dsw-alias-label-secondary);white-space:nowrap}.dsh-cc-secret{box-sizing:border-box;width:100%;max-width:210px;height:38px;border:1px solid var(--dsw-alias-border-secondary,rgba(0,0,0,.1));border-radius:8px;background:var(--dsw-specific-input-major,rgba(0,0,0,.025));display:flex;align-items:center;padding:0 14px;letter-spacing:3px;color:var(--dsw-alias-label-secondary)}
.dsh-cc-actions{display:flex;justify-content:flex-end;gap:4px}.dsh-cc-actions button,.dsh-cc-modal-head button{width:34px;height:34px;border:0;border-radius:8px;background:transparent;color:var(--dsw-alias-label-secondary);display:inline-flex;align-items:center;justify-content:center;cursor:pointer}.dsh-cc-actions button:hover:not(:disabled),.dsh-cc-modal-head button:hover{background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-primary)}.dsh-cc-actions .dsh-cc-danger:hover:not(:disabled){color:var(--dsw-alias-state-error-primary,#d54941);background:var(--dsw-alias-interactive-bg-hover-danger,rgba(213,73,65,.08))}
.dsh-cc-empty,.dsh-cc-state{margin:0;padding:64px 24px;text-align:center;color:var(--dsw-alias-label-secondary)}.dsh-cc-notice{margin:-8px 0 16px;padding:10px 12px;border-radius:8px;color:var(--dsw-alias-state-error-primary,#d54941);background:var(--dsw-alias-interactive-bg-hover-danger,rgba(213,73,65,.08))}
.dsh-cc-error{max-width:520px;margin:80px auto;padding:28px;border:1px solid var(--dsw-alias-border-secondary);border-radius:12px}.dsh-cc-error h2{margin:0 0 8px}.dsh-cc-error p{color:var(--dsw-alias-label-secondary)}.dsh-cc-error button{padding:8px 14px;border:1px solid var(--dsw-alias-border-secondary);border-radius:8px;background:transparent;color:inherit;cursor:pointer}
.dsh-cc-modal-backdrop{position:fixed;inset:0;z-index:1000;background:var(--dsw-alias-bg-mask,rgba(0,0,0,.34));display:flex;align-items:center;justify-content:center;padding:24px}.dsh-cc-modal{box-sizing:border-box;width:min(520px,100%);border:1px solid var(--dsw-alias-border-secondary,rgba(0,0,0,.12));border-radius:16px;background:var(--dsw-specific-dialog,var(--dsw-alias-bg-base,#fff));box-shadow:0 18px 60px rgba(0,0,0,.2);padding:24px;display:flex;flex-direction:column;gap:18px}.dsh-cc-modal-head{display:flex;align-items:center;justify-content:space-between}.dsh-cc-modal-head h2{margin:0;font-size:20px}.dsh-cc-modal-head button{font-size:24px}.dsh-cc-modal label{display:flex;flex-direction:column;gap:8px;font-weight:550}.dsh-cc-modal input{box-sizing:border-box;width:100%;height:44px;border:1px solid var(--dsw-alias-border-secondary,rgba(0,0,0,.14));border-radius:9px;background:var(--dsw-specific-input-major,transparent);color:var(--dsw-alias-label-primary);font:inherit;padding:0 12px;outline:0}.dsh-cc-modal input:focus{border-color:var(--dsw-alias-brand-primary,#4d6bfe);box-shadow:0 0 0 2px color-mix(in srgb,var(--dsw-alias-brand-primary,#4d6bfe) 14%,transparent)}.dsh-cc-modal input:disabled{opacity:.65}.dsh-cc-form-error{margin:-6px 0 0;color:var(--dsw-alias-state-error-primary,#d54941)}.dsh-cc-modal-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:4px}.dsh-cc-modal-actions>button:first-child{border:1px solid var(--dsw-alias-border-secondary);border-radius:9px;background:transparent;color:inherit;padding:10px 16px;cursor:pointer}.dsh-cc-sr{position:absolute!important;width:1px!important;height:1px!important;padding:0!important;margin:-1px!important;overflow:hidden!important;clip:rect(0,0,0,0)!important;white-space:nowrap!important;border:0!important}
@media(max-width:800px){.dsh-cc-page{padding:24px 16px 40px}.dsh-cc-header{align-items:stretch;flex-direction:column}.dsh-cc-primary{align-self:flex-start}.dsh-cc-table{min-width:760px}}
`

export function injectStyles(): () => void {
  return injectStylesOnce(STYLE_TAG, PANEL_CSS)
}
