/** Locale namespace for the Factory board. */
export const NS = 'factory'
/** Chinese board labels and status messages. */
export const zh = {
  'panel.title': 'LightCode Factory', 'panel.subtitle': '调度、评审并观测插件工作流', 'panel.refresh': '刷新', 'panel.loading': '正在读取工作流…', 'panel.loadMore': '加载更多', 'panel.loadingMore': '正在加载…', 'panel.error': '读取失败：{message}', 'icon.label': 'LightCode Factory',
  'task.create': '新建任务', 'task.dialogSubtitle': '选择工作流并填写任务参数', 'task.close': '关闭新建任务', 'task.select': '选择工作流', 'task.pluginHint': '参数由所选工作流插件提供', 'task.configuration': '任务配置', 'task.noParameters': '此工作流无需填写参数', 'task.fieldPlaceholder': '请输入{label}', 'task.required': '必填', 'task.sensitiveHint': '请勿填写密码、Token 等敏感信息', 'task.executionMode': '执行方式', 'task.immediate': '立即执行', 'task.scheduled': '定时执行', 'task.scheduleTime': '计划执行时间', 'task.scheduleHint': '使用当前设备时区，到点后进入执行队列', 'task.scheduleFuture': '请选择未来的执行时间', 'task.cancel': '取消', 'task.submit': '创建并执行', 'task.submitScheduled': '创建定时任务', 'task.submitting': '正在创建…', 'task.empty': '当前没有可执行的工作流', 'board.empty': '暂无工作流', 'card.open': '查看运行 {name}', 'card.created': '创建于 {time}', 'card.scheduled': '计划于 {time} 执行',
  'status.queued': '待调度', 'status.running': '执行中', 'status.review': '待评审', 'status.completed': '已完成', 'status.cancelled': '已取消', 'status.failed': '失败',
  'detail.back': '返回看板', 'detail.sheets': '工作流详情页签', 'detail.overview': '运行详情', 'detail.trace': '轨迹', 'detail.nodes': '工作流节点', 'detail.output': '节点输出', 'detail.events': '事件时间线', 'detail.none': '当前节点尚未产生输出', 'detail.stdout': '标准输出', 'detail.stderr': '标准错误', 'detail.duration': '{duration} 毫秒',
  'detail.runInfo': '运行信息', 'detail.status': '状态', 'detail.currentNode': '当前节点', 'detail.scheduledFor': '计划时间', 'detail.startedAt': '开始时间', 'detail.finishedAt': '完成时间', 'detail.elapsed': '总耗时', 'detail.workflow': '工作流', 'detail.allNodesComplete': '全部完成', 'detail.progress': '整体进度', 'detail.noEvents': '暂无运行事件', 'detail.exitCode': '退出码', 'detail.durationLabel': '耗时', 'detail.outputLines': '输出', 'detail.artifact': '产物', 'detail.dragHint': '拖拽查看全部节点', 'detail.selectNode': '选择输出节点', 'detail.collapse': '收起', 'detail.expand': '展开', 'detail.board': '工作流看板', 'detail.copy': '复制', 'detail.lines': '行', 'detail.nodesComplete': '个节点已完成', 'detail.dragMore': '向右滑动查看更多节点', 'detail.moveUp': '上移', 'detail.moveDown': '下移', 'detail.manualReview': '人工评审', 'detail.reviewHint': '所有节点已成功执行，请确认运行结果。',
  'action.cancel': '取消执行', 'action.reject': '取消工作流', 'action.approve': '评审通过',
  'node.pending': '待执行', 'node.running': '执行中', 'node.completed': '已完成', 'node.cancelled': '已取消', 'node.failed': '失败',
}
/** Keys shared by the board locale dictionaries. */
export type FactoryLocaleKey = keyof typeof zh
/** English board labels and status messages. */
export const en: Record<FactoryLocaleKey, string> = {
  'panel.title': 'LightCode Factory', 'panel.subtitle': 'Schedule, review, and observe plugin workflows', 'panel.refresh': 'Refresh', 'panel.loading': 'Loading workflows…', 'panel.loadMore': 'Load more', 'panel.loadingMore': 'Loading…', 'panel.error': 'Unable to load: {message}', 'icon.label': 'LightCode Factory',
  'task.create': 'New task', 'task.dialogSubtitle': 'Choose a workflow and configure its parameters', 'task.close': 'Close new task', 'task.select': 'Choose workflow', 'task.pluginHint': 'Parameters are provided by the selected workflow plugin', 'task.configuration': 'Task configuration', 'task.noParameters': 'This workflow requires no parameters', 'task.fieldPlaceholder': 'Enter {label}', 'task.required': 'Required', 'task.sensitiveHint': 'Do not enter passwords, tokens, or other sensitive information', 'task.executionMode': 'Execution mode', 'task.immediate': 'Run now', 'task.scheduled': 'Run later', 'task.scheduleTime': 'Scheduled time', 'task.scheduleHint': 'Uses this device timezone and enters the execution queue when due', 'task.scheduleFuture': 'Choose a future execution time', 'task.cancel': 'Cancel', 'task.submit': 'Create and run', 'task.submitScheduled': 'Create scheduled task', 'task.submitting': 'Creating…', 'task.empty': 'No executable workflows are available', 'board.empty': 'No workflows', 'card.open': 'Open run {name}', 'card.created': 'Created {time}', 'card.scheduled': 'Scheduled for {time}',
  'status.queued': 'Queued', 'status.running': 'Running', 'status.review': 'Review', 'status.completed': 'Completed', 'status.cancelled': 'Cancelled', 'status.failed': 'Failed',
  'detail.back': 'Back to board', 'detail.sheets': 'Workflow detail sheets', 'detail.overview': 'Run details', 'detail.trace': 'Trajectory', 'detail.nodes': 'Workflow nodes', 'detail.output': 'Node output', 'detail.events': 'Event timeline', 'detail.none': 'This node has no output yet', 'detail.stdout': 'Standard output', 'detail.stderr': 'Standard error', 'detail.duration': '{duration} ms',
  'detail.runInfo': 'Run information', 'detail.status': 'Status', 'detail.currentNode': 'Current node', 'detail.scheduledFor': 'Scheduled', 'detail.startedAt': 'Started', 'detail.finishedAt': 'Finished', 'detail.elapsed': 'Elapsed', 'detail.workflow': 'Workflow', 'detail.allNodesComplete': 'All nodes complete', 'detail.progress': 'Overall progress', 'detail.noEvents': 'No run events', 'detail.exitCode': 'Exit code', 'detail.durationLabel': 'Duration', 'detail.outputLines': 'Output', 'detail.artifact': 'Artifact', 'detail.dragHint': 'Drag to view all nodes', 'detail.selectNode': 'Select output node', 'detail.collapse': 'Collapse', 'detail.expand': 'Expand', 'detail.board': 'Workflow board', 'detail.copy': 'Copy', 'detail.lines': 'lines', 'detail.nodesComplete': 'nodes completed', 'detail.dragMore': 'Drag right to view more nodes', 'detail.moveUp': 'Move up', 'detail.moveDown': 'Move down', 'detail.manualReview': 'Manual review', 'detail.reviewHint': 'All nodes completed successfully. Please confirm the result.',
  'action.cancel': 'Cancel run', 'action.reject': 'Cancel workflow', 'action.approve': 'Approve review',
  'node.pending': 'Pending', 'node.running': 'Running', 'node.completed': 'Completed', 'node.cancelled': 'Cancelled', 'node.failed': 'Failed',
}
